// ─────────────────────────────────────────────────────────────────────────────
// Design-token build — Style Dictionary v4 (programmatic API).
//
// EVERYTHING here lives in and is generated by THIS package (web/lib/shared). The
// one source of truth is tokens/**.json; it compiles into several dist/ files.
// The "consumed by" column names who READS each file, not where it lives. Run via
// `node style-dictionary.config.mjs` (`build:tokens`). Style Dictionary is a
// devDependency — it never ships to consumers.
//
//   dist file (built here)    consumed by  contents
//   tokens.css                web/Opal     CSS vars — :root (primitives + light) + .dark
//   typography.css            web/Opal     Tailwind `@utility font-*` text presets
//   nativewind-theme.cjs      mobile       Tailwind `theme.extend` (class -> token)
//   nativewind-typography.cjs mobile       `.font-*` utilities (RN text styles)
//   native.js (+ .d.ts)       mobile       light/dark value maps + text presets for vars()
//
// Note: "opal" in the css/opal format names is the token SET (Opal's design tokens,
// now OWNED by shared) — not the Opal package, which is just a reader of the output.
//
// Two Style Dictionary concepts are used below:
//   • transform = edits ONE field of ONE token (here only its `name`). Per token.
//   • format    = prints ONE whole output file from all tokens. One per file.
//
// TOKEN MODEL — each JSON key IS the exact CSS var name (no prefix, no kebab
// mangling, so `alpha-grey-100-90` / `neon-amber-a60` survive byte-for-byte). The
// JSON nesting encodes tier + mode, which every filter below keys off via `path`:
//   primitives / size / typography  top-level    path = ["radius-12"]
//   semantic light                  under "light" path = ["light", "text-05"]
//   semantic dark                   under "dark"  path = ["dark",  "text-05"]
//   typography presets              under "text"  path = ["text", "heading-h1", "fontSize"]
//   e.g. semantic-light.json: { "light": { "text-05": { "value": "{alpha-grey-100-90}", "type": "color" } } }
//
// PIPELINE:  read JSON  ->  name transform  ->  each format prints a file  ->  dist/
// ─────────────────────────────────────────────────────────────────────────────

import StyleDictionary from "style-dictionary";

// Per-token accessors used by the formats below.
const leaf = (token) => token.path[token.path.length - 1]; // ["dark","text-05"] -> "text-05" (the var name)
const isColor = (token) => (token.type ?? token.$type) === "color";
const rawOriginal = (token) => token.original.value ?? token.original.$value; // authored, keeps "{ref}"
const resolved = (token) => token.value ?? token.$value; // refs followed, e.g. "#000000e5"

// `{a-b-c}` (or `{group.a-b-c}`) -> `var(--a-b-c)` (the reference's last path
// segment), then collapse internal whitespace (font-family values span lines).
// e.g. "{alpha-grey-100-90}" -> "var(--alpha-grey-100-90)"
function cssValue(rawValue) {
  return String(rawValue)
    .replace(/\{([^}]+)\}/g, (_, ref) => {
      const segs = ref.split(".");
      return `var(--${segs[segs.length - 1]})`;
    })
    .replace(/\s+/g, " ")
    .trim();
}

// rem/px/unitless string -> Number of px (RN style objects are unitless px).
// e.g. "0.75rem" -> 12, "2px" -> 2, "600" -> 600
function toPx(rawValue) {
  const v = String(rawValue).trim();
  if (v.endsWith("rem")) return parseFloat(v) * 16;
  if (v.endsWith("px")) return parseFloat(v);
  return Number(v);
}

// A CSS font-family stack -> its first family name (RN takes a single family).
// e.g. '"Hanken Grotesk", -apple-system, sans-serif' -> "Hanken Grotesk"
function firstFamily(stack) {
  return String(stack)
    .split(",")[0]
    .trim()
    .replace(/^["']|["']$/g, "");
}

// TRANSFORM (name) — the CSS var name is the verbatim LAST path segment. This is
// what stops SD's default kebab-casing from mangling Opal's names.
// e.g. path ["light","text-05"] -> name "text-05"  ->  emitted as --text-05
StyleDictionary.registerTransform({
  name: "name/opal-literal",
  type: "name",
  transform: (token) => leaf(token),
});

// FORMAT -> tokens.css (web/Opal). Primitives + light semantics go in :root; dark
// overrides go in .dark. Reads token.original (the authored "{ref}") so references
// stay `var(--x)` and dark mode flips at runtime. Typography presets (path[0] ===
// "text") are skipped here — they're emitted as @utility by css/opal-typography.
// e.g.  --text-05: var(--alpha-grey-100-90);   in :root
//       --text-05: var(--alpha-grey-00-95);    in .dark
StyleDictionary.registerFormat({
  name: "css/opal",
  format: ({ dictionary }) => {
    // Typography presets (path[0] === "text") are emitted as @utility blocks by
    // css/opal-typography, not as flat variables here.
    const rootTokens = dictionary.allTokens.filter(
      (t) => t.path[0] !== "dark" && t.path[0] !== "text"
    );
    const darkTokens = dictionary.allTokens.filter((t) => t.path[0] === "dark");
    const block = (sel, tokens) =>
      `${sel} {\n` +
      tokens
        .map((t) => `  --${leaf(t)}: ${cssValue(rawOriginal(t))};`)
        .join("\n") +
      `\n}\n`;
    return (
      "/* Generated by Style Dictionary. Source of truth: tokens/*.json. */\n" +
      "/* Do not edit by hand. */\n\n" +
      block(":root", rootTokens) +
      "\n" +
      block(".dark", darkTokens)
    );
  },
});

// FORMAT -> typography.css (web/Opal). Each preset under "text" becomes a Tailwind
// v4 @utility, byte-equivalent to Opal's hand-authored blocks. Values keep their
// `var()` refs (font families + height metrics) so they resolve from tokens.css.
// e.g.  text.heading-h1.{fontSize:"48px", fontWeight:"600", ...}  ->
//         @utility font-heading-h1 { font-size: 48px; font-weight: 600; ... }
const TYPO_PROP_ORDER = [
  ["fontFamily", "font-family"],
  ["fontSize", "font-size"],
  ["fontWeight", "font-weight"],
  ["lineHeight", "line-height"],
  ["letterSpacing", "letter-spacing"],
];
StyleDictionary.registerFormat({
  name: "css/opal-typography",
  format: ({ dictionary }) => {
    const presets = {};
    const order = [];
    for (const t of dictionary.allTokens) {
      if (t.path[0] !== "text") continue;
      const name = t.path[1];
      if (!presets[name]) {
        presets[name] = {};
        order.push(name);
      }
      presets[name][t.path[2]] = cssValue(rawOriginal(t));
    }
    let out =
      "/* Generated by Style Dictionary. Source of truth: tokens/typography-presets.json. */\n" +
      "/* Do not edit by hand. Typography preset utilities (web/Opal). */\n\n";
    for (const name of order) {
      out += `@utility font-${name} {\n`;
      for (const [key, cssProp] of TYPO_PROP_ORDER) {
        if (presets[name][key] !== undefined) {
          out += `  ${cssProp}: ${presets[name][key]};\n`;
        }
      }
      out += `}\n\n`;
    }
    return out;
  },
});

// FORMAT -> nativewind-theme.cjs (mobile). mobile/tailwind.config requires this as
// `theme.extend`. Colors map class -> var(--name) (themed at runtime by the vars()
// provider, mirroring web); radius/spacing are resolved to plain px numbers because
// RN can't use rem or var() for dimensions.
// e.g.  colors["text-04"] = "var(--text-04)"   borderRadius["12"] = 12   spacing["16"] = 16
StyleDictionary.registerFormat({
  name: "js/nativewind-theme",
  format: ({ dictionary }) => {
    // Colors: every color token name -> var(--name). Resolved at runtime by the
    // vars() provider (lightVars/darkVars), mirroring web's CSS-variable model.
    // De-dupe by name (a semantic name exists in both light & dark).
    const colorNames = [
      ...new Set(dictionary.allTokens.filter(isColor).map(leaf)),
    ].sort();
    const colors = Object.fromEntries(
      colorNames.map((n) => [n, `var(--${n})`])
    );
    // borderRadius: radius-* tokens -> resolved px numbers (rounded-12 etc.).
    const borderRadius = {};
    for (const t of dictionary.allTokens) {
      const n = leaf(t);
      const m = n.match(/^radius-(.+)$/);
      if (m) borderRadius[m[1] === "round" ? "full" : m[1]] = toPx(resolved(t));
    }
    // spacing: spacing-block-* / spacing-inline-* -> px numbers.
    const spacing = {};
    for (const t of dictionary.allTokens) {
      const n = leaf(t);
      const m = n.match(/^spacing-(?:block|inline)-(.+)$/);
      if (m) spacing[m[1]] = toPx(resolved(t));
    }
    const theme = { colors, borderRadius, spacing };
    return (
      "// Generated by Style Dictionary. Source of truth: tokens/*.json.\n" +
      "// Do not edit by hand. NativeWind `theme.extend` fragment for mobile.\n" +
      "module.exports = " +
      JSON.stringify(theme, null, 2) +
      ";\n"
    );
  },
});

// FORMAT -> native.d.ts (mobile). Hand-written types for native.js below — SD
// generates that JS, not its declarations, so they're spelled out here.
// `TextFont` is NOT defined here: it's the single canonical union in the neutral
// src/contracts/typography.ts (shared by web + mobile). We import it so that
// `textPresets` stays typed by that one source rather than a second native-only
// copy. (The relative `./contracts` resolves to dist/contracts/index.d.ts, which
// build:ts emits right after this build:tokens step.)
StyleDictionary.registerFormat({
  name: "dts/native-vars",
  format: () => {
    return (
      "// Generated by Style Dictionary. Do not edit by hand.\n" +
      'import type { TextFont } from "./contracts";\n' +
      "export declare const varsLight: Record<string, string>;\n" +
      "export declare const varsDark: Record<string, string>;\n" +
      "export interface TextPreset {\n" +
      "  fontFamily: string;\n" +
      "  fontSize: number;\n" +
      "  fontWeight: string;\n" +
      "  lineHeight: number;\n" +
      "  letterSpacing: number;\n" +
      "}\n" +
      "export declare const textPresets: Record<TextFont, TextPreset>;\n"
    );
  },
});

// FORMAT -> nativewind-typography.cjs (mobile). The RN counterpart of web's
// typography.css `@utility font-*` blocks: a `.font-<preset>` -> RN-text-style map
// that mobile/tailwind.config.js registers as NativeWind utilities (via tailwindcss
// `plugin` + addUtilities). This is what lets mobile write `font-heading-h1` exactly
// like web. Values share js/native-vars' textPresets resolution (same numeric
// magnitudes) but are serialized differently: CSS-ish px strings here (e.g. "48px")
// vs bare RN-style numbers there — NativeWind parses these strings into RN text styles.
// e.g.  text.heading-h1  ->  ".font-heading-h1": { fontFamily: "Hanken Grotesk",
//         fontSize: "48px", fontWeight: "600", lineHeight: "64px", letterSpacing: "-0.48px" }
StyleDictionary.registerFormat({
  name: "js/nativewind-typography",
  format: ({ dictionary }) => {
    // Single pass keyed by `.font-<name>`; prop order follows token order in
    // typography-presets.json (same as js/native-vars' textPresets below).
    const utilities = {};
    for (const t of dictionary.allTokens) {
      if (t.path[0] !== "text") continue;
      const cls = `.font-${t.path[1]}`;
      const decl = (utilities[cls] ??= {});
      const prop = t.path[2];
      const val = resolved(t);
      if (prop === "fontFamily") decl.fontFamily = firstFamily(val);
      else if (prop === "fontWeight") decl.fontWeight = String(val);
      else decl[prop] = `${toPx(val)}px`; // fontSize / lineHeight / letterSpacing
    }
    return (
      "// Generated by Style Dictionary. Source of truth: tokens/typography-presets.json.\n" +
      "// Do not edit by hand. NativeWind `font-*` typography utilities for mobile.\n" +
      "module.exports = " +
      JSON.stringify(utilities, null, 2) +
      ";\n"
    );
  },
});

// FORMAT -> native.js (mobile, ESM). The RN analog of web's `.dark`: two fully
// RESOLVED color maps the vars() provider swaps by color scheme, plus text presets
// as RN style objects. Uses resolved values (concrete hex/numbers) since RN has no
// var(). varsLight = primitives + light semantics; varsDark = primitives + dark.
// e.g.  varsLight["--text-05"] = "#000000e5"   varsDark["--text-05"] = "#fffffff2"
//       textPresets["heading-h1"] = { fontFamily: "Hanken Grotesk", fontSize: 48, ... }
StyleDictionary.registerFormat({
  name: "js/native-vars",
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter(isColor);
    const build = (excludeMode) => {
      const out = {};
      for (const t of colors) {
        if (t.path[0] === excludeMode) continue; // drop the other mode's overrides
        out[`--${leaf(t)}`] = String(resolved(t)); // resolved hex (primitive value)
      }
      return out;
    };
    const varsLight = build("dark"); // primitives + light semantic
    const varsDark = build("light"); // primitives + dark semantic
    // Typography presets as RN-ready style objects (resolved numbers + single family).
    const textPresets = {};
    for (const t of dictionary.allTokens) {
      if (t.path[0] !== "text") continue;
      const name = t.path[1];
      const prop = t.path[2];
      const preset = (textPresets[name] ??= {});
      const val = resolved(t);
      if (prop === "fontFamily") preset.fontFamily = firstFamily(val);
      else if (prop === "fontWeight") preset.fontWeight = String(val);
      else preset[prop] = toPx(val); // fontSize / lineHeight / letterSpacing
    }
    return (
      "// Generated by Style Dictionary. Source of truth: tokens/*.json.\n" +
      "// Do not edit by hand. Light/dark variable maps + text presets for mobile.\n" +
      "export const varsLight = " +
      JSON.stringify(varsLight, null, 2) +
      ";\n\nexport const varsDark = " +
      JSON.stringify(varsDark, null, 2) +
      ";\n\nexport const textPresets = " +
      JSON.stringify(textPresets, null, 2) +
      ";\n"
    );
  },
});

// Wire it together: load all token JSON, run the name transform on every token,
// then run each format to write its file. One platform is enough — the formats,
// not transforms, decide each file's shape.
const sd = new StyleDictionary({
  source: ["tokens/**/*.json"],
  log: { verbosity: "default", warnings: "warn" },
  platforms: {
    out: {
      // ONLY a name transform — value transforms are intentionally omitted so
      // token.value stays the exact authored literal (no hex/unit rewriting) and
      // token.original keeps the `{ref}` form the CSS formats depend on.
      transforms: ["name/opal-literal"],
      buildPath: "dist/",
      files: [
        { destination: "tokens.css", format: "css/opal" },
        { destination: "typography.css", format: "css/opal-typography" },
        { destination: "nativewind-theme.cjs", format: "js/nativewind-theme" },
        {
          destination: "nativewind-typography.cjs",
          format: "js/nativewind-typography",
        },
        { destination: "native.js", format: "js/native-vars" },
        { destination: "native.d.ts", format: "dts/native-vars" },
      ],
    },
  },
});

await sd.buildAllPlatforms();
