name: Run Zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
    paths:
      - ".github/**"

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-slim
    timeout-minutes: 45
    permissions:
      contents: read # needed to checkout the repo on private repos (no-op on public)
      security-events: write # needed for SARIF uploads
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # ratchet:astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: false
          version: "0.9.9"

      - name: Install zizmor from uv.lock
        run: uv sync --frozen --no-install-project --only-group zizmor

      - name: Run zizmor
        run: uv run --no-sync zizmor --format=sarif . > results.sarif
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@ba454b8ab46733eb6145342877cd148270bb77ab # ratchet:github/codeql-action/upload-sarif@codeql-bundle-v2.23.5
        with:
          sarif_file: results.sarif
          category: zizmor
