HIERARCHY_NODES_PREFIX = "/hierarchy-nodes"
HIERARCHY_NODES_LIST_PATH = ""
HIERARCHY_NODE_DOCUMENTS_PATH = "/documents"
HIERARCHY_NODES_SEARCH_PATH = "/search"

DOCUMENT_PAGE_SIZE = 50
HIERARCHY_NODE_SEARCH_LIMIT = 30
