name: "Setup Playwright"
description: "Sets up Playwright and system deps (assumes Python and Playwright are installed)"
runs:
  using: "composite"
  steps:
    - name: Cache playwright cache
      uses: runs-on/cache@a5f51d6f3fece787d03b7b4e981c82538a0654ed
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ runner.arch }}-playwright-${{ hashFiles('backend/requirements/default.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-playwright-

    - name: Install playwright
      shell: bash
      run: |
        playwright install chromium --with-deps
